/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,800;0,900;1,200&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="">
        <div className="grad h-[50vh]">
          {/* NavBar */}
          <Navbar />
          {/* Explore */}
        </div>
      </div>

      {/* Trending */}
      {/* Notable Collections */}
    </div>
  );
}
