/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import Image from "next/image";
import Collections from "../components/Collection";
import Explore from "../components/Explore";
import Spotlight from "../components/Spotlight";
import Navbar from "../components/Navbar";
import Notables from "../components/Notables";
import Trending from "../components/Trending";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Opensea2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,800;0,900;1,200&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="relative">
        <div className="grad">
          {/* NavBar */}
          <Navbar />
          <Explore />
        </div>
      </div>

      {/* Trending */}
      <Trending />
      <Collections />
      {/* Notable Collections */}
      <Notables />
      <Spotlight />
      <Footer />
    </div>
  );
}
